### ISSUE TITLE
[BUG] Long strings break out of text boxes

### ISSUE THREAD

**Issue by starchyunderscore** [Mistium/Origin-OS#10]
Version:
v4.2.2

Browser:
Mozilla Firefox 119.0 64-bit

Brief description:
When imputing numbers or text, the text will often wrap in a way that puts it outside of the bounds of the text box

Expected behavior:
The text will scroll in the text box or the text box will expand to fit the text

Current behavior:
The text escapes the text box

Images:
![Screenshot_20231027_210333](https://github.com/Mistium/Origin-OS/assets/102399926/8838650b-e402-4108-9fc9-39664ab75b28)
![Screenshot_20231027_205906](https://github.com/Mistium/Origin-OS/assets/102399926/afc5cb2d-3878-4503-bf40-560a7e591fed)
![Screenshot_20231027_205809](https://github.com/Mistium/Origin-OS/assets/102399926/aafc2d5d-73a7-443d-aa13-a10624c024d0)
![Screenshot_20231027_204934](https://github.com/Mistium/Origin-OS/assets/102399926/ce861f9e-c519-4771-8742-2dc2a9b0b292)

Additional notes:
Often the cursor does not follow the text in wrapping, and instead floats off the screen

**Comment by Mistium** [comment]
Yep I am aware of this. OSL's gui systems don't resize based on other components so I'll probably make it so that the text inside an input is scrollable but idk how easy that will be.

**Comment by Mistium** [comment]
[video (33).webm](https://github.com/Mistium/Origin-OS/assets/92952823/a1f3402d-d978-4ec9-9a1f-a4f02810658c)
I made a basic system for this but its a little buggy right now so ill work on it a bit more before uploading
