### ISSUE TITLE
[Bug] App Shows Up Even After Closed

### ISSUE THREAD

**Issue by rhel202** [Mistium/Origin-OS#100]
I closed the application  

Application is closed but is still rendering on the desktop, acts like it exists but is removed from all window data lists

**Comment by ThePandaDever** [comment]
Might be a caching problem.?
Though I don't know how origin catches windows so idk

**Comment by Mistium** [comment]
> Might be a caching problem.? Though I don't know how origin catches windows so idk

nope, if the app clone wasn't still open, it would clear the window from the display, but the window stays even when the screen cache is reset

**Comment by Mistium** [comment]
not sure if this bug still exists so im going to close this issue until i run into it
