### ISSUE TITLE
[Bug] Ghosting while dragging file on other windows

### ISSUE THREAD

**Issue by vio201** [Mistium/Origin-OS#106]
https://github.com/Mistium/Origin-OS/assets/97127104/33a3fe8e-8a4b-4f6a-a815-9117a470a89b

![image](https://github.com/Mistium/Origin-OS/assets/97127104/d8df4198-7bf1-4132-912a-b307e281d906)

**Comment by Mistium** [comment]
yea, this is just visual so it should be fine to leave this until i fix it accidentally or smth

**Comment by Mistium** [comment]
I think this is probably due to the can clock system in the kernel, might be able to fix it by allowing applications to become focused even when hovering and holding a file, should be a single if statement.

**Comment by Mistium** [comment]
fixed in 5.0.0
