### ISSUE TITLE
[SUGGESTION] Bracketed Methods

### ISSUE THREAD

**Issue by Mistium** [Mistium/Origin-OS#109]
Bracketed Methods

Example:
```js
test = ( 10 / 3 ).round
```

Would allow for more concise and readable osl code

Would require a little more work for the compiler

**Comment by Mistium** [comment]
I should be able to make this pretty easily

**Comment by Mistium** [comment]
![Screenshot 2024-05-06 at 11 42 20](https://github.com/Mistium/Origin-OS/assets/92952823/a371dc20-e3d5-4fbc-a8af-5875b56952fb)

DONE!

**Comment by Flufi-Boi** [comment]
you should add functions
