### ISSUE TITLE
[Suggestion] FSL support in origin

### ISSUE THREAD

**Issue by Mistium** [Mistium/Origin-OS#113]
Allow for fsl files in origin to be created and run, possible application support for gui once @ThePandaDever adds gui

https://github.com/ThePandaDever/Flufi-OS

**Comment by Mistium** [comment]
@ThePandaDever help meeeeee

**Comment by ThePandaDever** [comment]
help me with the fcl ext then yes :3

**Comment by ThePandaDever** [comment]
wild
