### ISSUE TITLE
[Suggestion] App store extra features

### ISSUE THREAD

**Issue by Mistium** [Mistium/Origin-OS#119]
run button after you have installed an app

normally start with bigger window

library should work properly

**Comment by ThePandaDever** [comment]
sounds farmilliar 😎

**Comment by ThePandaDever** [comment]
flufi launcher better

**Comment by ThePandaDever** [comment]
Uh huh

**Comment by Mistium** [comment]
added library and update and run buttons, plus a version number next to the name of the app

**Comment by Mistium** [comment]
added
