### ISSUE TITLE
[V.4.3.7] Going back to boot, switch tabs bugs it 

### ISSUE THREAD

**Issue by wolfieboy09** [Mistium/Origin-OS#12]
[Screen recording 2023-11-30 10.07.25 AM.webm](https://github.com/Mistium/Origin-OS/assets/105564186/66777297-3b30-47a2-9d65-bfc6841d5307)

So when you follow those steps, go OUT of the tab for a second, go back, and want to change the version thingy, it bugs out by switching the select version and confirming it. ChromeOS built-in recorder can't record it going quickly. It always does it with me (most of the time)

Edit: Think of the fast change like your holding `1 + space` but without pressing it

**Comment by Mistium** [comment]
didn't fix this idk why i closed it

**Comment by Mistium** [comment]
Fixed this in v2.4 of bios
