### ISSUE TITLE
brute force quick boot

### ISSUE THREAD

**Issue by koo1140** [Mistium/Origin-OS#121]
a link that forcelly quickly boots origin on latest version and show login popup
i want to quickly access origin, speed matters

**Comment by Mistium** [comment]
origin’s boot time is largely dependent on your network, but i bet i could make some kind of cache that if it detects no apps have changed or been updated, it doesn’t dowload them

**Comment by Mistium** [comment]
added caching to th eboot, so if you have all th efiles downloaded its basically gonna boot instantly

**Comment by ThatBeaverDev** [comment]
My browser caches it anyway i think, mine boots fast.
