### ISSUE TITLE
[Polish] Make a better Bin Icon and put it on the desktop by default

### ISSUE THREAD

**Issue by koo1140** [Mistium/Origin-OS#126]
w 2 line 5 -10 7 7 cont -7 7 cont -5 -10 cont 5 -10 line -6 7 -5 10 cont 5 10 cont 6 7
![image](https://github.com/Mistium/Origin-OS/assets/112756430/552b4307-5e7b-4897-8f28-3bd2a3fa2400)

**Comment by Mistium** [comment]
idk how to make a better bin icon, also the bin is on the dock so this is kinda redundant
