### ISSUE TITLE
[NEW OSL] New rendering stuff

### ISSUE THREAD

**Issue by ThePandaDever** [Mistium/Origin-OS#139]
lines
```
line x1 y1 x2 y2
```

striped lines
```
stripe x1 y1 x2 y2 stripe_length stripe_offset
```

thats all i can think of :P

**Comment by Mistium** [comment]
done this plus a dotted line
![Screenshot 2024-06-12 at 14 07 25](https://github.com/Mistium/Origin-OS/assets/92952823/a290ef15-c60f-4fd5-ad34-c5d30a3c7f93)
