### ISSUE TITLE
OriginOS VersionLoader Test Layering Issue

### ISSUE THREAD

**Issue by wolfieboy09** [Mistium/Origin-OS#14]
Part of the text is being hidden on the boot loader. The text is getting hidden from the logo

![image](https://github.com/Mistium/Origin-OS/assets/105564186/0fd2bee4-21db-41a4-82ce-63d990ee8260)

![image](https://github.com/Mistium/Origin-OS/assets/105564186/7cb09701-57bd-4051-88cc-785ad698ef36)

**Comment by Mistium** [comment]
Small screen, ill move the logo, also thats the actual system not the version loader

**Comment by wolfieboy09** [comment]
Oh okay

**Comment by Mistium** [comment]
![Uploading Screenshot 2023-11-30 at 17.07.23.png…]()

fixed
