### ISSUE TITLE
[Suggestion] Window stuff

### ISSUE THREAD

**Issue by ThePandaDever** [Mistium/Origin-OS#142]
make it so u can change the min window size like
```
window "min_size" 400 300
```
for example :3

change how you make minimised windows
```
window "minimised" {"text":"Epic"}
```
would be equivelant to (or replaces) `minimised_text = "Epic"`

but stuff like
```
window "minimised" {"text":"Haii\n:3","size":[100,75]}
```
:3

or just make a custom minimised tag like mainloop
```

window "minimised" {"type":"custom","size":[100,75]}

mainloop:
  goto 0 0
  text "haiii :3" 10
import win-buttons

minimised:
  goto 0 0
  text "im smaller now :)"
```

**Comment by ThePandaDever** [comment]
pretty simple

**Comment by Mistium** [comment]
how tf does the minimised windows thing work

**Comment by Mistium** [comment]
added min_size

**Comment by Mistium** [comment]
the minimised thing is kinda bad so not happening
