### ISSUE TITLE
[Bidmas] Add Bidmas

### ISSUE THREAD

**Issue by RattusDong** [Mistium/Origin-OS#144]
Why is there no bidmas?

![maxresdefault](https://github.com/Mistium/Origin-OS/assets/147535283/4a3eafd9-af42-44f0-ba23-4cadd742f6cb)

**Comment by Mistium** [comment]
no

**Comment by Mistium** [comment]
<details>
  <summary>Fortnite</summary>
  
  Why did you look?
</details>

**Comment by Mistium** [comment]
already a thing technically
