### ISSUE TITLE
App right side thingy dupelacated

### ISSUE THREAD

**Issue by wolfieboy09** [Mistium/Origin-OS#15]
So with this app
![image](https://github.com/Mistium/Origin-OS/assets/105564186/e835f365-44b8-4338-a98e-b6a8f577cd0b)

The corner does this:
![image](https://github.com/Mistium/Origin-OS/assets/105564186/84318b42-5d92-440d-959a-9a7e9943ba18)

It will works, but its annoying I guess

**Comment by Mistium** [comment]
ohhhhh

it shouldn't do that, its because the studio app is part of the system itself and not osl, but it used to import the window buttons and now i replaced them, ill add something to remove that from happening give me a second

**Comment by Mistium** [comment]
should be fixed now in v4.3.8
