### ISSUE TITLE
[Bug] In the "To do" app the text can go off the task

### ISSUE THREAD

**Issue by vio201** [Mistium/Origin-OS#156]
https://github.com/Mistium/Origin-OS/assets/97127104/de19a69d-2675-45c4-9d5a-47c85320c514

**Comment by Mistium** [comment]
i mean, not too big of an issue ig, i can make it just cut off or wrap, but wrapping would be substantially harder

**Comment by Mistium** [comment]
this probably wont be fixed, its a very minor app and i dont have the interest rn for it lmao
