### ISSUE TITLE
Window randomly Flips

### ISSUE THREAD

**Issue by JusttNoone** [Mistium/Origin-OS#16]
https://github.com/Mistium/Origin-OS/assets/150234551/403cf907-c697-42a0-9007-55ac3f8f6d19

IDK

**Comment by wolfieboy09** [comment]
Woah thats wierd yet cool

**Comment by Mistium** [comment]
thats kinda on purpose

the window has a minimum width so it can't resize to anything under that, but if you resize to the other side greater than that minimum it will just resize onto that side

**Comment by Mistium** [comment]
not really a bug

**Comment by JusttNoone** [comment]
also

**Comment by JusttNoone** [comment]
https://github.com/Mistium/Origin-OS/assets/150234551/22e028a3-d121-4626-9339-ebd8dfc75420

here, it doesnt work 😭

**Comment by JusttNoone** [comment]
wait

**Comment by JusttNoone** [comment]
wrong recording 🤣

**Comment by Mistium** [comment]
Damn lmao

**Comment by JusttNoone** [comment]
https://github.com/Mistium/Origin-OS/assets/150234551/31763067-0991-4414-a359-a7003d151b5d

**Comment by wolfieboy09** [comment]
I found the calculator issue, and was about to put it in as an issue here

**Comment by Mistium** [comment]
yep, thats a known issue

**Comment by Mistium** [comment]
This is not an issue, in fact kinda a feature :)

**Comment by wolfieboy09** [comment]
Oh! I may have also found another bug, let me submit that one
