### ISSUE TITLE
[Suggestion] Theme system for origin

### ISSUE THREAD

**Issue by koo1140** [Mistium/Origin-OS#160]
add themes on whole ui like default, frutiger aero, etc

**Comment by Mistium** [comment]
#159 is kinda the same thing

**Comment by koo1140** [comment]
i mean like
also change how ui looks

**Comment by koo1140** [comment]
shapes

**Comment by Mistium** [comment]
how

**Comment by Mistium** [comment]
what

**Comment by koo1140** [comment]
idk
web 2.0 gloss theme

**Comment by Mistium** [comment]
![image](https://github.com/Mistium/Origin-OS/assets/92952823/87e8649e-af95-4100-8f9a-2bb55068d28e)
? 🤮

**Comment by koo1140** [comment]
no bruh

**Comment by Mistium** [comment]
then wtf do you mean 😭

**Comment by koo1140** [comment]
sec

**Comment by koo1140** [comment]
https://frutiger-aero.org/frutiger-aero

**Comment by Mistium** [comment]
> https://frutiger-aero.org/frutiger-aero

🤮

**Comment by Mistium** [comment]
ew

**Comment by yuri-kiss** [comment]
dang
