### ISSUE TITLE
[BUG] Origin doesnt ask for clipboard permissions on v5.1.4

### ISSUE THREAD

**Issue by MILO123PRO** [Mistium/Origin-OS#167]
![imagen](https://github.com/user-attachments/assets/245b2c6d-26fb-44d1-a9dd-feb9a4137318)

Even allowing the permission manually.. Things like updating the pfp dont work.

**Comment by Mistium** [comment]
you need to paste to allow origin to access the clipboard

**Comment by Mistium** [comment]
might make a modded version of the clipboard extension

**Comment by MILO123PRO** [comment]
okay
