### ISSUE TITLE
[v4.3.7] Changing window size makes apps go away if dragged away

### ISSUE THREAD

**Issue by wolfieboy09** [Mistium/Origin-OS#18]
[Screen recording 2023-11-30 5.54.26 PM.webm](https://github.com/Mistium/Origin-OS/assets/105564186/bd67bff5-9ac4-4e62-9ca1-2848541cb326)

So if you drag apps out when zoomed out, and zoom back in, go back to 100% zoom, the app disappears until zoomed out.

**Comment by Mistium** [comment]
this video doesn't really show any bugs

**Comment by wolfieboy09** [comment]
When you zoom out, the app box goes past the border and stays their until interacted again.

**Comment by Mistium** [comment]
it should tho?
