### ISSUE TITLE
[v4.2.2] Taskbar bugged out

### ISSUE THREAD

**Issue by wolfieboy09** [Mistium/Origin-OS#24]
# Disclaimer
I KNOW its an old version, but wanted to point this out

![image](https://github.com/Mistium/Origin-OS/assets/105564186/496de885-1324-4a2f-bb56-95aa2863d08f)

So I loaded into v4.2.2, and get this

**Comment by Mistium** [comment]
Yea this is an old problem, I've already fixed this
