### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Ninjaofbl** [Mistium/Origin-OS#3]
-There is just a ton of lag in the OS. (Think it is just normal right now)
-Drag and drop is also not in a good place as well.
The OS is really cool and how you made it as a real one!

**Comment by Mistium** [comment]
Which version did you download? The newest ones run at 40fps idle on my computer
I'm still working on optimising it and yes i know drag and drop is buggy.

Can you send a screenshot of your activity application?

**Comment by Mistium** [comment]
It now runs at 40-60fps idle on my 2015 macbook pro
