### ISSUE TITLE
[v4.0.0] When resizing window, the drag box comes along

### ISSUE THREAD

**Issue by wolfieboy09** [Mistium/Origin-OS#34]
![image](https://github.com/Mistium/Origin-OS/assets/105564186/c54b1679-ac5a-4b56-b422-397a371ed9ba)
The dark grey box in the back is the drag box, and then you resize a window, it comes along

**Comment by Mistium** [comment]
Yep ik

**Comment by Mistium** [comment]
fixed in v4.4.1
