### ISSUE TITLE
[v4.4.0] THE OSL INTERPRETER HAS A MASSIVE PERFORMANCE ISSUE

### ISSUE THREAD

**Issue by Mistium** [Mistium/Origin-OS#37]
Guess what, me from the future... You are an idiot, you are fully parsing every command even if its inside a false if statement, you should just make it skip every false if statement until it finds where the if statement ends

while count_thing > 0 (

if command has "(" count_thing += 1
if command has ")" count_thing -= 1

)

else statements should be handled fine by this system

**Comment by Mistium** [comment]
FIXED!! the osl interpretor now only parses the code into a readable format when the system requires it to run a line of code

**Comment by Mistium** [comment]
I’m not stupid, I made all of statements just jump positions now :)

**Comment by Mistium** [comment]
i’m also not stupid, i switched to a full ast and now it just parses and runs what it needs to

**Comment by Flufi-Boi** [comment]
this still isnt fixed

**Comment by Mistium** [comment]
> this still isnt fixed

i will end you

**Comment by Flufi-Boi** [comment]
😎
