### ISSUE TITLE
mistium.github.io

### ISSUE THREAD

**Issue by burnsboyamazing** [Mistium/Origin-OS#44]
Not a bug here. Just a mistium website. @wolfieboy09 Uploading the image of the mistium website.
![Screenshot 2023-12-25 9 30 27 PM](https://github.com/Mistium/Origin-OS/assets/154830140/011738fe-f73a-4e0d-9825-8765d23c6a0e)

**Comment by Mistium** [comment]
lmao, i made this a while ago, yea i know part of it is broken

**Comment by burnsboyamazing** [comment]
@wolfieboy09 Uploading the screen recording for the support of ChromeOS.
[Screen recording 2023-12-25 9.29.04 PM.webm](https://github.com/Mistium/Origin-OS/assets/154830140/c238627e-9062-4098-b741-8c39e3afa165)

**Comment by wolfieboy09** [comment]
What about me? I was pinged twice here

**Comment by wolfieboy09** [comment]
Plus I have a Windows 11 laptop

**Comment by burnsboyamazing** [comment]
@wolfieboy09 Uploading the screen recording of the ChromeOS + Windows 11.
[Screen recording 2023-12-26 10.44.07 AM.webm](https://github.com/Mistium/Origin-OS/assets/154830140/201661cd-ea42-4558-8d70-09d58ab94b49)

**Comment by Mistium** [comment]
i'm very confused

**Comment by burnsboyamazing** [comment]
@wolfieboy09 In Gmail fixes the issue with the website in ChromeOS not Windows 10, but Windows 11.
![Screenshot 2023-12-26 10 48 03 AM](https://github.com/Mistium/Origin-OS/assets/154830140/f9c3c40d-0e6d-48bd-b327-6f51ac093caa)

**Comment by wolfieboy09** [comment]
The HTML of the site is coded badly, so it shows up like that.


![image](https://github.com/Mistium/Origin-OS/assets/105564186/117a9aad-375a-4e28-bed5-6b465a222138)

**Comment by burnsboyamazing** [comment]
This is not the HTML site this is in Gmail.
![Screenshot 2023-12-26 11 07 41 AM](https://github.com/Mistium/Origin-OS/assets/154830140/ee069f80-d304-4657-967f-02d4cdc88a60)

**Comment by burnsboyamazing** [comment]
Uploading the image of the HTML site in Gmail. @wolfieboy09 ChromeOS, not Windows 11.
![Screenshot 2023-12-26 11 11 07 AM](https://github.com/Mistium/Origin-OS/assets/154830140/f24b3e40-0b13-432d-a757-3047bad9ce17)

**Comment by Mistium** [comment]
> Uploading the image of the HTML site in Gmail. @wolfieboy09 ChromeOS, not Windows 11. ![Screenshot 2023-12-26 11 11 07 AM](https://private-user-images.githubusercontent.com/154830140/292893121-f24b3e40-0b13-432d-a757-3047bad9ce17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MDc1MjQsIm5iZiI6MTcwMzYwNzIyNCwicGF0aCI6Ii8xNTQ4MzAxNDAvMjkyODkzMTIxLWYyNGIzZTQwLTBiMTMtNDMyZC1hNzU3LTMwNDdiYWQ5Y2UxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQxNjEzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzA1MjgyMGQ3YzJkYWNiOTI0MGZhMzEwNzNhMDk3MTM3ZjFiY2U3ZmI3OTc2MjRmZTkxZjhkMzE1ZTA3YTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zAuIPnLwLyWc5FgCZWen83Xt7OG9U5m42NcAvjj5uWo)

this isn't something i'm working on or fixing so don't worry about it lol

**Comment by burnsboyamazing** [comment]
Uploading the image of the HTML site in https://mistium.github.io with Gmail, in ChromeOS, not Windows 10.
![Screenshot 2023-12-26 11 16 58 AM](https://github.com/Mistium/Origin-OS/assets/154830140/264e1f91-0534-4081-af4b-c82bcebd7317)
