### ISSUE TITLE
[Bug Report/Suggestion] Accent colour management

### ISSUE THREAD

**Issue by vernacular7** [Mistium/Origin-OS#47]
My first issue !
I’ll start by introducing myself. My name is vernacular, and I have (and I’m sure you have too) felt very sad about the unfunctionality of the accent colour feature in originOS.

 Okay.. enough with the dramatic monologue.
 The feature works.. sort of. It only seems to take effect in the right click menus. The settings page for it doesn’t update the colour, but if you change it, it displays only in certain circumstances. I’m guessing it’s because of how the new(ish) networking handles accent colour linking to accounts.
 
 I think the page for accent colour deserves a remaster! 😛

**Comment by Mistium** [comment]
I've been meaning to update the accent colour page for a while now, I have a full sketch for it, I'll try fix all the bugs

**Comment by Mistium** [comment]
![Screenshot 2024-01-07 at 16 59 48](https://github.com/Mistium/Origin-OS/assets/92952823/7f49d376-846e-492e-b9fb-6e0ae1b18d3e)

proved the update account command works, now to implement a "sync colour to account" button in settings

**Comment by Mistium** [comment]
not done lol

**Comment by Mistium** [comment]
done!

![image](https://github.com/Mistium/Origin-OS/assets/92952823/802bab18-cc50-4f99-96a7-ea079d49b5bf)
