### ISSUE TITLE
Suggestion - "Play sound from url ---" OSL

### ISSUE THREAD

**Issue by vernacular7** [Mistium/Origin-OS#50]
Uh yeahh. Please add it 

:3 Pwetty pwease :3 pweeeeeease.... pwease... ;3 with a chewwy on top... pweasseeeee

**Comment by vernacular7** [comment]
> :( fine

nooo don't be sadddd

**Comment by Mistium** [comment]
lol, I’ll work on this for v4.6.4

**Comment by vernacular7** [comment]
> lol, I’ll work on this for v4.6.4

yay thank u 💗

**Comment by Mistium** [comment]
> > lol, I’ll work on this for v4.6.4
> 
> yay thank u 💗

Np lol

**Comment by Mistium** [comment]
https://github.com/Mistium/Origin-OS/issues/40
