### ISSUE TITLE
[Suggestion] Improved Studio

### ISSUE THREAD

**Issue by koo1140** [Mistium/Origin-OS#51]
most likely, id allow the user to preview an app as they make it so you can position the elements without needing to run the app to check the positioning every time 

do the thign u sayd rn but make a new prewiew type: "edit" where u can reposition stuff and resize / change text (it detects chanegs and updates the code)

**Comment by vernacular7** [comment]
> most likely, id allow the user to preview an app as they make it so you can position the elements without needing to run the app to check the positioning every time 
> 
> 
> 
> do the thign u sayd rn but make a new prewiew type: "edit" where u can reposition stuff and resize / change text (it detects chanegs and updates the code)

this would be an awesome feature in any development app, you should go for it!

**Comment by Mistium** [comment]
This is likely a planned feature, i'll work on adding a way to preview different elements on applications in real time. Maybe i'll make it so you can load an app and then send data to it for what to display.

**Comment by Mistium** [comment]
Added this in the form of the layout builder application. You can export it as osl and then add logic to it in studio
