### ISSUE TITLE
[Suggestion] python

### ISSUE THREAD

**Issue by koo1140** [Mistium/Origin-OS#59]
run python instead of osl

except no modules (maybe later)
builtin: time, random, string

print("hi") ~ outputs to console "hi" without quotes

other python stuff...

module:

```py
time: time.sleep(1) # waits i second
date: time.hour time.minute time.day
```

random:
```py
random.shuffle("hey") # out example: eyh
random.int(2, 20) # returns a number between 2 and 20
```

`string.ascii # returns alphabet symbols numbers`

import module_name
module_name.function(param1, param2 ...)

**Comment by Mistium** [comment]
would be very complex to add a full python interpreter

**Comment by Sasytoremember** [comment]
lua may be easier to implement

**Comment by Mistium** [comment]
> lua may be easier to implement

That may be true

**Comment by koo1140** [comment]
friendly reminder

**Comment by Mistium** [comment]
still unlikely to be added, i have a regex to split up python now but there are too many things id have to add to actually make python. Id be better off making a full new project to make a python interpreter in scratch.
