### ISSUE TITLE
Booting OriginOS 4.7.1 has no wallpaper.

### ISSUE THREAD

**Issue by TeknikSpace** [Mistium/Origin-OS#60]
While booting 4.7.1, there's no wallpaper, and it just looks weird.
It appears that the wallpaper just doesn't render or load.

[OriginOS Bug.webm](https://github.com/Mistium/Origin-OS/assets/107750535/8bcc47cd-25c0-44c0-90ed-d693834c22ba)

**Comment by Mistium** [comment]
Fixed in v4.7.2
