### ISSUE TITLE
[Suggestion] Multiline Select In Text Boxes

### ISSUE THREAD

**Issue by koo1140** [Mistium/Origin-OS#61]
![image](https://github.com/Mistium/Origin-OS/assets/112756430/750806be-baa8-428e-93d4-2929524f0270)

**Comment by Mistium** [comment]
doesn't exist yet, but i plan on adding multiline select

will likely happen when i make multiline inputs and thats going to take a while

**Comment by ThePandaDever** [comment]
"when i make multiline inputs" u mean never? lmao

**Comment by Mistium** [comment]
> "when i make multiline inputs" u mean never? lmao

😭

**Comment by Mistium** [comment]
Still need to figure out how to do multiline in a single component, probably use smth like

textbox width height id rounding text_colour lineheight

**Comment by ThePandaDever** [comment]
yeah, just do it 😎

**Comment by Mistium** [comment]
added
