### ISSUE TITLE
[Bug] Null contact

### ISSUE THREAD

**Issue by meepstertron** [Mistium/Origin-OS#64]
![image](https://github.com/Mistium/Origin-OS/assets/62438310/57a0a6cd-7142-4590-9f65-a4f52c1527be)
if you press cancel on the popup a contact called Null is created this is because of when you press cancel the input returns Null (Nothing) this can be fixed by canceling making a contact if the input is Null ;)

**Comment by Mistium** [comment]
huh

**Comment by Mistium** [comment]
oops lol, theres a user called null so it may be interfering tho i doubt it
