### ISSUE TITLE
[Suggestion] Image Support

### ISSUE THREAD

**Issue by koo1140** [Mistium/Origin-OS#65]
origin should be able to view image files like:
.png
.jpg
.svg
.ico

etc..

**Comment by Mistium** [comment]
png file support in origin?

**Comment by koo1140** [comment]
well just keep it temporary if the file is too big (notify that the file wont be saved) or smth like this

**Comment by Mistium** [comment]
> well just keep it temporary if the file is too big (notify that the file wont be saved) or smth like this

hmm, maybe, milo has offered to supply a bunch of extra file storage so the origin free tier may be going to 50mb soon

**Comment by Mistium** [comment]
Added
