### ISSUE TITLE
[Suggestion] fix all apps and keep it all fixed so it always works (at least in latest version)

### ISSUE THREAD

**Issue by koo1140** [Mistium/Origin-OS#67]
bcz when u get a bug it looks very bad

**Comment by Mistium** [comment]
what happens?

**Comment by Mistium** [comment]
can you send a screenshot?

**Comment by koo1140** [comment]
there are like lots of bugs

**Comment by koo1140** [comment]
most of them is dimensions and resizing bugs
eg: clock can be resized

holding on a frame makes select in desktop and when u touch app edge it resizes
etc

**Comment by koo1140** [comment]
start menu is too big for smaller windows

**Comment by Mistium** [comment]
> most of them is dimensions and resizing bugs eg: clock can be resized
> 
> holding on a frame makes select in desktop and when u touch app edge it resizes etc

Clock? What?

**Comment by Mistium** [comment]
> most of them is dimensions and resizing bugs eg: clock can be resized
> 
> holding on a frame makes select in desktop and when u touch app edge it resizes etc

It should only resize if you click?

**Comment by Mistium** [comment]
> start menu is too big for smaller windows

Use a bigger monitor idk, or zoom out in browser

**Comment by koo1140** [comment]
> > start menu is too big for smaller windows
> 
> Use a bigger monitor idk, or zoom out in browser

i can resize the browser but it looks wierd when its big

**Comment by Mistium** [comment]
![Screenshot 2024-03-06 at 16 21 50](https://github.com/Mistium/Origin-OS/assets/92952823/17de53ef-38de-40f6-b476-c2e28e27e796)
this?

**Comment by Mistium** [comment]
i made it so apps are pulled from the repo, so its possible that will fix this issue? since i can jsut update the apps post launch to fix bugs
