### ISSUE TITLE
👾 Small Visual bug with control center widget 

### ISSUE THREAD

**Issue by vernacular7** [Mistium/Origin-OS#74]
@Mistium 
That’s all there is to say! Very small issue, may be local, but I’m not sure. I can’t look at the code on my tablet to see what’s causing it right now, but here’s a rundown :)

When the speed icon is selected, the moon icon has a tiny anomaly… **see attached files.**
![IMG_1228](https://github.com/Mistium/Origin-OS/assets/132183833/adec2699-4e33-4474-a738-fc4f264290c9)
![IMG_1227](https://github.com/Mistium/Origin-OS/assets/132183833/e8bd06b9-d871-447c-b931-0ba40c8e971f)

**Also, hai mist :3**

Great progress and amazing work as always!

**Comment by MILO123PRO** [comment]
I can confirm its **not** local.

**Comment by Mistium** [comment]
Yes that’s because the performance mode decreases the number of individual segements that are rendered in the cutcircle system in icn files

**Comment by Mistium** [comment]
Fixed
