### ISSUE TITLE
[Suggestion] mobile support

### ISSUE THREAD

**Issue by koo1140** [Mistium/Origin-OS#79]
i think just make a virtual keyboard that pops up when need or when user presses a button or swipes or smth to open keyboard
also on phones we should have a simplified version so one for computer and one for phones
for phone ones you can use different ui layout and stuff

just a suggestion cuz this may be hard to do idk

**Comment by Mistium** [comment]
i can definitely attempt this, but origin isnt exactly intended to be used on mobile

**Comment by Mistium** [comment]
probably not happening, but might do it eventually
