### ISSUE TITLE
[Suggestion] Update Layout Builder

### ISSUE THREAD

**Issue by koo1140** [Mistium/Origin-OS#80]

**Comment by Mistium** [comment]
what kinds of things should i add?

**Comment by koo1140** [comment]
maybe a way to resize liek this:
![image](https://github.com/Mistium/Origin-OS/assets/112756430/51514cea-acc1-4bf0-94e0-16dd7b05d5bb)
i mean i can hold click to resize the component or hold it to move it or rotate

**Comment by Mistium** [comment]
hmm, that could be cool, ill think about it

**Comment by Mistium** [comment]
ill do this eventually, or someone else might do it for me 🤷🏻‍♀️
