### ISSUE TITLE
[bug] ... (see screenshot)

### ISSUE THREAD

**Issue by koo1140** [Mistium/Origin-OS#83]
![image](https://github.com/Mistium/Origin-OS/assets/112756430/f123bcab-38d9-4312-a725-dee0c0553b02)
i think it would look better wihout any icon

**Comment by Mistium** [comment]
i just need more icons, ill figure smth out

**Comment by koo1140** [comment]
that dock icon looks bad tho

**Comment by Mistium** [comment]
![Screenshot 2024-03-14 at 17 58 38](https://github.com/Mistium/Origin-OS/assets/92952823/7f374bca-c005-42c6-bc6f-fd19187a0fc7)
fixed

**Comment by Mistium** [comment]
> that dock icon looks bad tho

https://cdn.discordapp.com/emojis/803473973781725224.webp?size=96&quality=lossless
