### ISSUE TITLE
[Suggestion] Add Descriptions On Hover

### ISSUE THREAD

**Issue by koo1140** [Mistium/Origin-OS#85]
![image](https://github.com/Mistium/Origin-OS/assets/112756430/1bfe6c99-4f8a-4eb7-8f7f-e21227634d92)
what in the world this button does? (the one in corner)

**Comment by Mistium** [comment]
ahhh, like a text description thing, sure

**Comment by Mistium** [comment]
that button pauses the activity list so it doesnt update the times

**Comment by Mistium** [comment]
Added, use the modifier "tooltip" to display a small popup text

data = "A basic square"
square 100 100 10 : tooltip#data
