### ISSUE TITLE
[bug] even after resizing activity app it still hides text in networking tab

### ISSUE THREAD

**Issue by koo1140** [Mistium/Origin-OS#86]
![image](https://github.com/Mistium/Origin-OS/assets/112756430/d988198d-6ccb-4394-98c8-c1212b3a1a57)
(PS: should add a clear button)

**Comment by Mistium** [comment]
Sob emoji

**Comment by Mistium** [comment]
yea this was just so that the activity stuff didn't overflow, ig i could show the rest. will attempt now

**Comment by Mistium** [comment]
fixed
