### ISSUE TITLE
[suggestion] sorry this app is no longer compatible

### ISSUE THREAD

**Issue by koo1140** [Mistium/Origin-OS#87]
![image](https://github.com/Mistium/Origin-OS/assets/112756430/1620e10b-ebe2-45ba-8faa-344e257d4caf)

code (made with layout builder + small manual edits):
```
// Edit the number below to change the size of the layout
size = 1
window "dimensions" 1280 * size 740 * size
window "show"
goto -556 * size -119 * size
c #fff
text "Sorry, this app has an error or no longer compatible." 22 
goto -0 * size 165 * size
c #fff
icon x 14
```

**Comment by Mistium** [comment]
this likely wont be added, since osl errors dont actually stop the system from running a script
