### ISSUE TITLE
[Suggestion] Save App Progress

### ISSUE THREAD

**Issue by koo1140** [Mistium/Origin-OS#88]
for ex if i navigate to a folder in files app then i close and open again, it opens the app at that folder, also save sliders, buttons, togges, cheekboxes etc..

- this doesnt save to account, it only saves temporary

**Comment by koo1140** [comment]
yup

**Comment by ThePandaDever** [comment]
Could be done with app data so it could just be the dev to make that.

**Comment by Mistium** [comment]
turns out this is incredibly complicated to do so...
