### ISSUE TITLE
[BUG] Key release not registered in some scenarios

### ISSUE THREAD

**Issue by starchyunderscore** [Mistium/Origin-OS#9]
Version:
v4.2.2

Browser:
Mozilla Firefox 119.0 64-bit

Brief description:
When imputing characters, if you hit `tab`, the character will continue to input, even after you have released the key

Expected behavior:
Key will register as no longer being pressed

Current behavior:
Key acts as if it is still pressed

Video:
https://youtu.be/c_YMGEvhZFs

**Comment by Mistium** [comment]
Aware of this one too. Still unable to find a fix but I'll keep trying lol

**Comment by Mistium** [comment]
FIXED!

This now no-longer happens in v4.3.6
