### ISSUE TITLE
[suggestion] add a reboot button somewhere in the settings

### ISSUE THREAD

**Issue by koo1140** [Mistium/Origin-OS#90]
it would NOT reload the page, instead just resets everything to normal state, kills all apps etc
also resets app data (from another suggestion)

**Comment by koo1140** [comment]
[app data](https://github.com/Mistium/Origin-OS/issues/88)

**Comment by Mistium** [comment]
im still kinda confused about this one, just open the start menu and click the power icon and it reboots
