### ISSUE TITLE
[suggestions] add more colors

### ISSUE THREAD

**Issue by koo1140** [Mistium/Origin-OS#91]
![image](https://github.com/Mistium/Origin-OS/assets/112756430/6c281b2c-8a7b-4b13-b278-b1d94ba12640)
- dock color
- quicksettings color
- color influence RGB > for ex if i make red influence 50, when anything is displayed its red color value gets +50, same goes for blue and green

**Comment by Mistium** [comment]
![Screenshot 2024-03-15 at 11 53 31](https://github.com/Mistium/Origin-OS/assets/92952823/07c0d5a5-f79d-4607-8001-803da3ed91d9)
done
