### ISSUE TITLE
[suggestion] file sharing

### ISSUE THREAD

**Issue by koo1140** [Mistium/Origin-OS#98]
![image](https://github.com/Mistium/Origin-OS/assets/112756430/016bf1f0-a0f7-47d4-ab2e-5995c37e4c2f)

**Comment by Mistium** [comment]
ill add a tool that lets you send and receive files between users

**Comment by koo1140** [comment]
you could make file preview instead of downloading

**Comment by Mistium** [comment]
> you could make file preview instead of downloading

? how, in order to preview you need to download it, you could just choose to not save it

**Comment by Mistium** [comment]
i made an app to send files now sooooo...
